### PR TITLE
2.0.7: plus = gpt 5.6; pro = astra

### PR DESCRIPTION
**Pull request by totec448-spec**
## Result
This single snapshot commit contains the final 2.0.7 file changes on top of main; intermediate development commits are excluded. It integrates the browser ownership and native input fixes. Browser handoffs keep one elected document across navigation and worker suspension; Goal/Loop and finish requests retain exact turn ownership, retry temporary API failures, and deliver generated follow-ups through the next tool response. Provider destination, model and reasoning remain consistent across settings changes.

Native file workflows include bounded opt-in artifact downloads and image handling. Connector refresh now handles validated native cards with no Refresh action, while the companion popup requires confirmed protocol compatibility. Usage accounting recognizes the observed Sol model alias and uses current configurable cached-input rates. macOS notification actions receive the required alert-style packaging declaration.

## Validation
- Complete local integration suite: 3155 passed, 23 skipped before the final focused fixes; isolated shutdown tests included.
- Final affected suites: 177 passed; canonical artifact fixture follow-up: 16 passed. Finish test timer isolation also has a failing-before/passing-after regression. TypeScript and staged-diff checks pass.
- Shared-tree finish/exec regression rerun: 163 passed, 3 skipped.
- Public snapshot privacy checks pass. Maintainer logs and local session evidence are excluded.
- Windows/macOS/Linux CI all pass against snapshot 7c38fcb (run 34140556583). Local Windows installation completed; installed main/preload/renderer bytes match a fresh build of the final runtime.

Live Windows testing confirms ordered, exactly-once queued-stage delivery and one active worker. Model compliance with completing every stage before calling finish remains distinct from transport correctness. Actual packaged macOS notification/focus behavior and native Linux behavior are not claimed as locally verified.

PR #93 startup/reopen behavior is covered. Its mandatory residency and Dock-removal proposal is deferred because it changes existing close preferences. Broader product proposals remain separately scoped.

### CODE REVIEW

**Comment by totec448-spec** [comment]
Source disposition after the open-issue/PR audit, at afa383298629e89f7b9a5348f4af5f1133bedb93:

- Incorporated with focused integration corrections: #88 custom instructions, #87 per-worker model/effort schema, #86 Project-preserving continuation, #39 exact handoff progress, #92 native plugin-refresh/no-Refresh handling, #94 opt-in artifact saving, #95 custom API request snapshots, #100 browser selection, #101 companion compatibility recovery, and #102 structural/localized model-picker handling.
- Already represented by published source: #62 installer ACL. #68 overlaps the existing worker broker and the schema delivered by #87.
- Partly adopted: #47 stale revival validation, without its old Firefox package/protocol; #78 relevant tunnel fixes and truthful worker/tool status, without the unrelated new browser/host tool surface. #93 startup/reopen lifecycle is covered, while mandatory macOS residency/Dock removal remains separate because it would override the existing user preference.
- Kept separate: #43 external Codex Desktop authority, #18 alternative Loop scheduler, #17 Power Agent capability expansion, #16 changed Goal completion policy, and #15 hard read-only Plan semantics. The desktop staged-plan UI does not implement #15's permission fence.

Issue #49 and #51 are closed against verified published-main source/regressions. Fifteen issues now link to this review candidate with explicit evidence limits. The remaining feature requests and affected-device/account reports stay open; candidate inclusion is not a release or platform-acceptance claim.
